language: swift
osx_image: xcode9.3

branches:
  only:
    - dev
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

cache:
  directories:
    - $HOME/.cocoapods/

before_install:
  - rvm install ruby-2.5.1
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - pod update
script:
  - set -o pipefail
  - xcodebuild -workspace ListSample.xcworkspace -scheme ListSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - swiftlint
